### ISSUE TITLE
Prebuilt_tools problem

### ISSUE THREAD

**Issue by jasonlee1001** [SI-RISCV/hbird-e-sdk#2]
请问prebuilt_tools https://pan.baidu.com/s/1eUbBlVc 已经不能连结了, 是否有更新连结的地址呢?

**Comment by myron2009** [comment]
你好，我刚测试了一下，网盘打开和下载一切正常，请重新试一下！

**Comment by jasonlee1001** [comment]
你好，还是不行。网页上回応的信息是 “分享链接中有违规或违法内容，无法继续查看”。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by myron2009** [comment]
留下你的“有效”邮箱！

**Comment by jasonlee1001** [comment]
> 留下你的“有效”邮箱！

jasonlhb@gmail.com
谢谢您 !
